name: github_search
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^3.1.0
  rxdart: ^0.23.1
  equatable: ^1.0.2
  http: ^0.12.0+4
  url_launcher: ^5.4.1
  connectivity: ^0.4.6+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true